List<String> articleTitle = [
  "Be Aware of Your Surroundings",
  "Maintain Phone and Emergency Contacts",
  "Learn Self-Defense",
  "Avoid Excessive Alcohol Consumption",
  "Utilize Safety Apps and Tools",
  "Trustworthy Transportation",
  "Carry a Personal Safety Device",
  "Stay Informed",
  "Trust Your Intuition",
  "Community Engagement",
  "Push Yourself",
  "Don't Fear in Panic Situation",
  "Solidarity",
  "Courage",
  "Practice Caution with Strangers",
];
List<String> imageSliders = [
  "assets/images/women_carousel/1.jpeg",
  "assets/images/women_carousel/2.jpeg",
  "assets/images/women_carousel/3.jpg",
  "assets/images/women_carousel/4.jpg",
  "assets/images/women_carousel/5.jpg",
  "assets/images/women_carousel/6.jpg",
  "assets/images/women_carousel/7.jpeg",
  "assets/images/women_carousel/8.jpg",
  "assets/images/women_carousel/9.jpeg",
  "assets/images/women_carousel/10.jpg",
  "assets/images/women_carousel/11.jpg",
  "assets/images/women_carousel/12.jpg",
  "assets/images/women_carousel/13.jpg",
  "assets/images/women_carousel/14.jpg",
  "assets/images/women_carousel/15.png"
];