name: vsafe
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Project Dependencies
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  carousel_slider: ^4.2.1
  video_player: ^2.6.1
  drop_shadow: ^0.1.0
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.11
  fluttertoast: ^8.2.1
  curved_labeled_navigation_bar: ^2.0.2
  get: ^4.6.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  email_auth: ^1.0.0
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.0.0
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  lottie: ^2.3.2
  animated_splash_screen: ^1.3.0
  flutter_advanced_drawer: ^1.3.5
  sqflite: ^2.2.8+4
  image_picker: ^0.8.7+5
  uuid: ^3.0.7
  firebase_storage: ^11.2.2
  liquid_pull_to_refresh: ^3.0.1
  share_plus: ^7.0.0
  auth: ^8.2.0+2
  background_sms: ^0.0.4
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  email_otp: ^2.0.1
  shake: ^2.2.0
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  flutter_background_service_ios: ^2.4.0
  flutter_local_notifications: ^14.1.1
  vibration: ^1.7.7
  audioplayers: ^1.0.1
  flutter_slidable: ^3.1.0
  flutter_faq: ^1.0.1+1
  rating_dialog: ^2.0.4
  store_redirect: ^2.0.1
  http: ^0.13.5
  cached_network_image: ^3.2.3
  emoji_picker_flutter: ^1.6.1
  firebase_messaging: ^14.6.5
  flutter_notification_channel: ^2.0.0
  gallery_saver: ^2.3.2
  intl: ^0.18.1
  external_app_launcher: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/women_carousel/
    - assets/images/safety_tips_images/
    - assets/images/safety_tips_images/manage_phone_contact/
    - assets/images/safety_tips_images/awareness/
    - assets/images/safety_tips_images/alcohol_consumption/
    - assets/images/safety_tips_images/safety_app_and_tools/
    - assets/images/safety_tips_images/trustworthy_transportation/
    - assets/images/safety_tips_images/personal_safety_device/
    - assets/images/safety_tips_images/stay_informed/
    - assets/images/safety_tips_images/trust_your_intuition/
    - assets/images/safety_tips_images/community_engagement/
    - assets/images/safety_tips_images/push_yourself/
    - assets/images/safety_tips_images/do_not_fear/
    - assets/images/safety_tips_images/solidarity/
    - assets/images/safety_tips_images/courage/
    - assets/images/safety_tips_images/practice_caution_with_strangers/
    - assets/images/emergency_numbers/
    - assets/images/nearby_service/
    - assets/images/icon/
    - assets/images/intro_images/
    - assets/images/fake_call/
    - assets/animations/intro_app_animations/
    - assets/animations/other_animations/
    - assets/videos/safety_videos/
    - assets/audio/caller_tune.mp3


  fonts:
    - family: KaushanScript-Regular
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.ttf

    - family: Courgette-Regular
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf

    - family: NovaSlim-Regular
      fonts:
        - asset: assets/fonts/NovaSlim-Regular.ttf

    - family: PTSans-Regular
      fonts:
        - asset: assets/fonts/PTSans-Regular.ttf

    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Dosis-Regular
      fonts:
        - asset: assets/fonts/Dosis-Regular.ttf

    - family: EBGaramond-Regular
      fonts:
        - asset: assets/fonts/EBGaramond-Regular.ttf

    - family: Rajdhani-Regular
      fonts:
        - asset: assets/fonts/Rajdhani-Regular.ttf

    - family: Acme-Regular
      fonts:
        - asset: assets/fonts/Acme-Regular.ttf

    - family: BebasNeue-Regular
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
